/*
 * This source file was generated by the Gradle 'init' task
 */
package combattourpartourjava.Cli;

import combattourpartourjava.Application.Factory.HerosFactory;
import combattourpartourjava.Domain.IClasseHeros;

public class App {
    IClasseHeros hero = HerosFactory.creer("Rogue");

     static void main(String[] args) {
        System.out.println(new App().hero);
    }
}
